version: '2'
services:
  webui:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /mnt/storage/camera/data:/var/www/app/data
      - ./cronjob/yiantcopy.sh:/opt/yidownload/yiantcopy.sh
    ports:
      - "5000:80"
    restart: always
    mem_limit: 100M
    env_file:
      .env