version: '2'
services:
  webui:
    build:
      context: webui/
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    restart: always
    cpuset: "0"
    volumes:
      - ./data:/app/data
    env_file:
      .env
  cronjob:
    build:
      context: cronjob/
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
    restart: always
    env_file:
      .env