version: '2'
services:
  webui:
    build:
      context: .
      dockerfile: Dockerfile
    image: phuonglm/yi-hack-webui
    volumes:
      - /mnt/exthdd/cctv/data:/var/www/app/data
      # Dev mode
      - ./cronjob/yiantcopy.sh:/opt/yidownload/yiantcopy.sh
      - ./cronjob/yi-hack-v5.sh:/opt/yidownload/yi-hack-v5.sh
      #- ./webui/templates:/var/www/app/templates
      #- ./webui/scripts:/var/www/app/scripts
      #- ./webui/libs:/var/www/app/libs
      #- ./webui/index.php:/var/www/app/index.php
    ports:
      - "0.0.0.0:5001:80"
      - "0.0.0.0:5005-5010:5005-5010"
      - "0.0.0.0:21:21"
    restart: always
    mem_limit: 70M
    env_file:
      .env