version: '2'
services:
  webui:
    build:
      context: .
      dockerfile: Dockerfile
    image: phuonglm/yi-hack-webui
    volumes:
      - /mnt/exthdd/cctv/data:/var/www/app/data
      # - ./cronjob/yiantcopy.sh:/opt/yidownload/yiantcopy.sh
      # - ./webui/templates:/var/www/app/templates
      # - ./webui/scripts:/var/www/app/scripts
      # - ./webui/libs:/var/www/app/libs
    ports:
      - "0.0.0.0:5001:80"
    restart: always
    mem_limit: 50M
    env_file:
      .env
    restart: always